### ISSUE TITLE
Kill bower cache?

### ISSUE THREAD

**Issue by kellyselden** [heroku/heroku-buildpack-emberjs#10]
I'm trying to debug an issue with my deploy, and the bower cache is looking suspicious. Is there a command in the buildpack or the heroku dashboard that will kill all the caches?

**Comment by kellyselden** [comment]
So I found the command to kill cache `heroku repo:purge_cache -a appname`, but the same deployment issue keeps on happening:

```
vendor-dca70bc….js:2 Uncaught ReferenceError: jQuery is not defined(anonymous function) @ vendor-dca70bc….js:2
package-hint-historic-resolver-71f754b17933ad8d36278facc26450e0.js:1 Uncaught TypeError: define is not a function(anonymous function) @ package-hint-historic-resolver-71f754b17933ad8d36278facc26450e0.js:1
```

**Comment by kellyselden** [comment]
Closing for now because I think it was a npm dep that was temporarily fubared.

**Comment by hone** [comment]
@kellyselden we should be [clearing the bower cache on changes to bower.json](https://github.com/heroku/heroku-buildpack-ember-cli-deploy/commit/bd48497e9f49f1d2d569518a8a1da68e30d7e47b).
