### ISSUE TITLE
Option to disable Fastboot

### ISSUE THREAD

**Issue by zeppelin** [heroku/heroku-buildpack-emberjs#13]
Currently if `ember-cli-fastboot` is present in `package.json` there is no option to op-out from serving the app in Fastboot mode. This is not desired when a feature or two is not compatible with Fastboot (yet), but the app works fine with the static buildpack, which would be fine for ex. a review app. The problem here is that the app can't be deployed without Fastboot anymore, since the entry from `package.json` can't be removed once features like the Fastboot service is used across the app.

**Comment by edmorley** [comment]
This buildpack has been deprecated (c06c1e31291c24f71e8d84225727887506c3c897), and it's also no longer possible for changes to be made to it, due to the issues mentioned in #61.
