### ISSUE TITLE
Enable compression (gzip)

### ISSUE THREAD

**Issue by sgasser** [heroku/heroku-buildpack-emberjs#14]
Hi,

compression (gzip) is not enabled.

Could we enable it?

**Comment by hone** [comment]
Are you using fastboot?

**Comment by sgasser** [comment]
Yes

**Comment by hone** [comment]
You'll need to setup gzip on your own. Ideally, I'd have a addon that 
would automate it but I'm not there yet. I've setup gzip support on the 
fastboot website.

You can use the `ember-cli-deploy-gzip` addon.
https://github.com/ember-fastboot/fastboot-website/blob/master/package.json#L33

There's also some config you'll need to do:
https://github.com/ember-fastboot/fastboot-website/blob/master/config/deploy.js#L6-L9

Also, in server you need to write some code to serve it. 
https://github.com/ember-fastboot/fastboot-website/blob/master/fastboot-server.js#L38

Hope that helps.

**Comment by sgasser** [comment]
Thx @hone 

gzip working with your hack.

Should gzip be the default in this buildpack?

**Comment by hone** [comment]
np. glad you got it working. I'm not sure how to make it default for 
fastboot since I don't really want to be modifying your `package.json`. 
The best path would probably be figuring out a way to front fastboot 
apps with the static buildpack then nginx can handle it.

**Comment by ghost** [comment]
And if I'm not using fastboot?

**Comment by oskarrough** [comment]
Hi, how about WITH fastboot but without ember-cli-deploy?

**Comment by hone** [comment]
Sorry, but you'll have to roll your own gzip compression in node until I
can figure a way to sit fastboot behind nginx.

**Comment by ivanhueso** [comment]
How can I gzip with Fastboot enabled? I follow @hone steps but i don't understand the third one

    Also, in server you need to write some code to serve it.
    https://github.com/ember-fastboot/fastboot-website/blob/master/fastboot-server.js#L38

What do you mean with this @hone . Where can I change this on my app??

Best,
Ivan Hueso

**Comment by zeppelin** [comment]
@ivanhueso @hone There is a much simpler hack to get gzip working.

- The buildpack [installs `fastboot-cli`](https://github.com/heroku/heroku-buildpack-ember-cli-deploy/blob/master/buildpack/mrblib/buildpack/commands/compile.rb#L61-L64) to run the app *if the `ember-fastboot` command is not available*
- `fastboot-cli` is running `fastboot-app-server`, which [has gzip support](https://github.com/ember-fastboot/fastboot-app-server/blob/master/src/fastboot-app-server.js#L18).

All that has to be done is:
- Fork `fastboot-cli`,  [add the `gzip: true` option](https://github.com/zeppelin/fastboot-cli/blob/enable-gzip/bin/ember-fastboot#L39)
- Add the forked repo to your app's `package.json` (`"fastboot-cli": "zeppelin/fastboot-cli#enable-gzip"`).

The buildpack will still tell you it can't detect the command, but the app will run with gzip enabled nonetheless. Feel free to use [my fork](https://github.com/zeppelin/fastboot-cli/tree/enable-gzip) until I the [PR](https://github.com/ember-fastboot/fastboot-cli/pull/2) gets merged.

**Comment by oskarrough** [comment]
Forcing HTTPS was the change that made gzip work for me. Like this:

```
// Procfile
web: node fastboot-server.js

// fastboot-server.js
const FastBootAppServer = require('fastboot-app-server');

let server = new FastBootAppServer({
  distPath: 'dist',
  gzip: true,
  // Force HTTPS. Also required for GZIP to work.
  beforeMiddleware(app) {
    app.use((request, response, next) => {
      if (request.headers['x-forwarded-proto'] === 'https') {
        return next();
      } else {
        return response.redirect(301, `https://${request.hostname}${request.url}`);
      }
    });
  }
});

server.start();
```

**Comment by edmorley** [comment]
This buildpack has been deprecated (c06c1e31291c24f71e8d84225727887506c3c897), and it's also no longer possible for changes to be made to it, due to the issues mentioned in #61.
