### ISSUE TITLE
remote: ArgumentError: invalid json

### ISSUE THREAD

**Issue by alidcast** [heroku/heroku-buildpack-emberjs#15]
I'm getting the following error:

```
remote: ArgumentError: invalid json
```

I'm using: 

```
  #engines
  "node": "6.4.0",
  "npm": "3.10.7",
  "ember-cli": "2.8.0"

```

Not sure what is causing it as, as `ember build` and `ember fastboot --serve-assets` and `ember deploy production` both work locally.

**Comment by alidcast** [comment]
^ I had accidently posted the issue meant for ember-cli-deploy (which I resorted to using), as it runs buildpack succesfully, but returns an [error running](https://github.com/heroku/heroku-buildpack-ember-cli-deploy/issues/6) `ember deploy production`.

**Comment by hone** [comment]
Can you paste the entire build output?
