### ISSUE TITLE
Proxying 

### ISSUE THREAD

**Issue by jholt1** [heroku/heroku-buildpack-emberjs#16]
Was wondering what would be the best solution to have a proxy similar to the https://github.com/tonycoco/heroku-buildpack-ember-cli#api-proxy

Looking to use this buildpack as I want to use fastboot

Thanks 😁

**Comment by Dhaulagiri** [comment]
@jholt1 the underlying static buildpack has [support for proxying](https://github.com/heroku/heroku-buildpack-static#proxy-backends).  Will that do what you are looking for?

**Comment by jholt1** [comment]
> When not using fastboot, the static buildpack uses nginx to efficiently serve static assets while also handling HTML5 pushState, proxying, and other common frontend hosting configurations.

From this and https://github.com/heroku/heroku-buildpack-static/search?utf8=%E2%9C%93&q=proxies&type=Code

It seems that you can only add proxies if you are not using fastboot

**Comment by hone** [comment]
@jholt1 that's correct, we currently only support proxying when not using fastboot. I'm still investigating how to run fastboot behind nginx effectively.

**Comment by edmorley** [comment]
This buildpack has been deprecated (c06c1e31291c24f71e8d84225727887506c3c897), and it's also no longer possible for changes to be made to it, due to the issues mentioned in #61.
