### ISSUE TITLE
Usage with pipeline

### ISSUE THREAD

**Issue by mmahalwy** [heroku/heroku-buildpack-emberjs#17]
I am noticing that when I 'Promote App' from staging to production in Heroku's pipeline workflow, it uses the previous env variables. I guess it's because they are bundled into the assets, hence why

**Comment by hone** [comment]
That's correct. This isn't unique to ember, but any asset pipeline whether that's the rails asset pipeline or webpack. The JS bundle contains the env vars after build, which won't get updated on promote. There are some hacks that do some runtime replacement that work around this issue like [heroku-js-runtime-env](https://github.com/mars/heroku-js-runtime-env) which you might want to check out.

**Comment by hone** [comment]
I'm closing this for now, since it's a platform level issue that I'll be pushing internally to solve. Thank you for raising it and sorry I don't have a better answer. :(

**Comment by dbinetti** [comment]
Any update on this @hone?

**Comment by hone** [comment]
@ike-delorenzo anything you can say here? This is the asset rebuild on promote issue we've been talking about with pipelines.

**Comment by dbinetti** [comment]
Just wondering if this wound up going anywhere, @hone @ike-delorenzo ?

**Comment by benkingcode** [comment]
Does this mean that Ember apps can't be used with Pipelines at all? Seems like a big oversight 👀

**Comment by dbinetti** [comment]
That's correct, @dbbk   It's a minor irritation, but still would be great if @hone or @ike-delorenzo or someone could let us know if it's solvable.

**Comment by dbinetti** [comment]
So if anyone has the bash skills, this is what @mars is doing.  He's running this in a .profile.d directory; I assume you could do something similar directly in a .profile file.  But basically the idea is to allow the bash script to replace the variables within the slug.  

I'm not nearly skilled enough to give this a try, but if it inspires anyone great...

```
#!/bin/bash

# Fail immediately on non-zero exit code.
set -e
# Debug, echo every command
#set -x

# Each bundle is generated with a unique hash name
# to bust browser cache.
js_bundle=/app/build/static/js/main.*.js

if [ -f $js_bundle ]
then

  # Get exact filename.
  js_bundle_filename=`ls $js_bundle`
  
  echo "Injecting runtime env into $js_bundle_filename (from .profile.d/inject_react_app_env.sh)"

  # Render runtime env vars into bundle.
  ruby -E utf-8:utf-8 \
    -r /app/.heroku/create-react-app/injectable_env.rb \
    -e "InjectableEnv.replace('$js_bundle_filename')"
fi
```

**Comment by Dhaulagiri** [comment]
To reiterate what @hone said, this is a fundamental limitation in how ember apps are built.  That said, if you don't need fastboot there is [another ember buildpack](https://github.com/heroku/heroku-buildpack-ember-cli) that we use which implements a hacky solution to this problem which has worked for us for the past 2+ years without major issue.

It works by rewriting the config into your app when you promote so config vars are updated to match the new environment.

**Comment by dbinetti** [comment]
glorious!  wow, there the whole time and didn't see it.  WFM
