### ISSUE TITLE
Hooks

### ISSUE THREAD

**Issue by ghost** [heroku/heroku-buildpack-emberjs#18]
I can't seem to find any concept of hooks (before build hook, etc.) in this repo. The old ember buildpack repo contained them. 

Any thoughts?

https://github.com/tonycoco/heroku-buildpack-ember-cli.git

**Comment by Macmee** [comment]
the old pack allowed you to provide a custom NGINX configuration which is a dealbreaker for me.

**Comment by Blackening999** [comment]
How can I install compass with this build pack?

**Comment by edmorley** [comment]
This buildpack has been deprecated (c06c1e31291c24f71e8d84225727887506c3c897), and it's also no longer possible for changes to be made to it, due to the issues mentioned in #61.
