### ISSUE TITLE
"yarn.lock" file and I get "bower not found".

### ISSUE THREAD

**Issue by ghost** [heroku/heroku-buildpack-emberjs#19]
If I push my project with "yarn.lock" file I got this error: `bower not found`. Why?

**Comment by Dhaulagiri** [comment]
@johnunclesam are you able to share a more complete build output?

**Comment by hone** [comment]
yarn support in the [node buildpack](https://github.com/heroku/heroku-buildpack-nodejs), which we use here to power the `npm` dependency story. we'll have to take a look into if this is a broader issue.

**Comment by Dhaulagiri** [comment]
@johnunclesam I tried this out on one of our apps using yarn and this buildpack and didn't get any bower-related errors.  Can you provide a little more detail on your setup and we can try to dig in some more?

**Comment by Dhaulagiri** [comment]
@johnunclesam this should be working, so I'm going to close this. Feel free to re-open if you have any additional detail.
