### ISSUE TITLE
Invalid buildpack error message

### ISSUE THREAD

**Issue by cibernox** [heroku/heroku-buildpack-emberjs#2]
Seems that there is an error in the readme. Running this line:

```
$ heroku buildpacks:set https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/emberjs.tgz
```

results in 

```
Invalid buildpack `heroku/emberjs`
```

**Comment by hone** [comment]
Thanks for the report. Looks like an issue with `npm` which the heroku toolbelt uses sadly. :( I documented a workaround in  311e76c.
