### ISSUE TITLE
Enable compression (gzip) without fastboot

### ISSUE THREAD

**Issue by ghost** [heroku/heroku-buildpack-emberjs#20]
In this issue (https://github.com/heroku/heroku-buildpack-emberjs/issues/14) they spoke about gzip when using Fastboot.

And if not?

**Comment by Dhaulagiri** [comment]
@johnunclesam it should enabled by default [via the static buildpack](https://github.com/heroku/heroku-buildpack-static#features) which is used by this buildpack.  Are you seeing differently?

**Comment by ghost** [comment]
Yes, in my Chrome I see total 900KB instead of 240KB (which is the size Heroku tells me when I deploy). And in "Content-Encoding" I see nothing (in "Network" Tab).

**Comment by Dhaulagiri** [comment]
@johnunclesam I'm not able to reproduce this when I create a [fresh app](https://ember-buildpack-non-fast.herokuapp.com/) from [this Heroku button](https://github.com/heroku/ember-js-getting-started) that uses this buildpack.  Do you have a custom static.json defined or any other config that might overriding the default behavior?

**Comment by ghost** [comment]
Dear @Dhaulagiri 3 minutes ago I tried with `https://example.herokuapp.com` and everything ok. But If I try with `http://example.com` which is a CNAME to that, it is not working in my Chrome. Strange affair.

If I test with http://gzipwtf.com/ the same `http://example.com` it **works**. Chrome no. Why this?

Just HTTPS problem?

I'm using Namecheap for domain and CNAME.

I have a free dyno and not an ssl endpoint (which is just too expensive).

**Comment by hone** [comment]
https should not have an affect. Can you provide a repro case for us to dig into this more?

**Comment by edmorley** [comment]
This buildpack has been deprecated (c06c1e31291c24f71e8d84225727887506c3c897), and it's also no longer possible for changes to be made to it, due to the issues mentioned in #61.
