### ISSUE TITLE
Feature request: changeable env param

### ISSUE THREAD

**Issue by lancedikson** [heroku/heroku-buildpack-emberjs#22]
Hey, what about make it possible to change `--production` to any other thing? For instance, I'd like to use `--staging`.

**Comment by acorncom** [comment]
Believe this is close to a duplicate of https://github.com/heroku/heroku-buildpack-ember-cli-deploy/issues/3

**Comment by lancedikson** [comment]
@acorncom, yep, but no moves in that issue ¯\_(ツ)_/¯

**Comment by Dhaulagiri** [comment]
I think we can probably close this and try to ship #5

**Comment by lancedikson** [comment]
Great! I've tested the fork made for that PR. It works for me.
