### ISSUE TITLE
 ENOENT No bower.json present    

### ISSUE THREAD

**Issue by dephora** [heroku/heroku-buildpack-emberjs#24]
With a freshly created Ember 2.11 app, when trying `git push heroku master`(with no changes made to the app) I'm receiving ` ENOENT No bower.json present Error running: bower --allow-root install 2>&1` ...

I've tried the following:

- Uninstalled and reinstalled npm, bower, heroku
- Added a global .bowerrc with `{ "allow_root": true }`
- Push from both bash and zsh
- Given full permissions on bower.json and package.json, as well as the app folder

- Cleared the bower and npm cache, dumped the folders and reinstalled. 
- sudo chown -R $USER:$GROUP ~/.cache
- sudo chown -R $USER:$GROUP ~/.npm
- sudo chown -R $USER:$GROUP ~/.config

Here is the tail end at the failure point.

remote: -----> Caching build
remote:        Clearing previous node cache
remote:        Saving 2 cacheDirectories (default):
remote:        - node_modules
remote:        - bower_components (nothing to cache)
remote:
remote: -----> Build succeeded!
remote: -----> Fetching buildpack heroku/ember-cli-deploy
remote: -----> ember-cli detected
remote: -----> Installing bower dependencies
remote: bower               Error running: bower --allow-root install 2>&1
remote:             ENOENT No bower.json present
remote: -----> Failed trying to compile heroku/ember-cli-deploy
remote:  !     Push rejected, failed to compile emberjs app.
remote:
remote:  !     Push failed
remote: Verifying deploy....
remote:
remote: !	Push rejected to enigmatic-beach-93884.
remote:
To https://git.heroku.com/enigmatic-beach-93884.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/enigmatic-beach-93884.git'

Any ideas would be appreciated.

**Comment by ghost** [comment]
Same problem without bower.json, no longer used now.

**Comment by hone** [comment]
Thanks, I was under the impression this wasn't something I had to fix. I'll look at only running `bower` if `bower.json` is detected. /cc @rondale_sc

**Comment by hone** [comment]
This should is fixed by [#8](https://github.com/heroku/heroku-buildpack-ember-cli-deploy/pull/8).
