### ISSUE TITLE
Support for HTTP basic auth

### ISSUE THREAD

**Issue by bartocc** [heroku/heroku-buildpack-emberjs#25]
https://github.com/tonycoco/heroku-buildpack-ember-cli used to provide a way to configure http basic auth.

heroku-buildpack-emberjs is based upon https://github.com/heroku/heroku-buildpack-static but this buildpack does not provide, yet, a way to configure http basic auth. There is a PR ready though : https://github.com/heroku/heroku-buildpack-static/pull/45.

Is there a way to configure http basic auth before this PR is merged ? For example, configuring heroku-buildpack-emberjs to use https://github.com/doinginc/heroku-buildpack-static.git#basic-auth instead of https://github.com/heroku/heroku-buildpack-static ?

Thx
Julien

**Comment by hone** [comment]
@bartocc there currently isn't, but I think the feature that would come out of this would be overriding buildpacks. I'd have to think on what a good design is there.

**Comment by oskarrough** [comment]
Is there a workaround for now?

**Comment by edmorley** [comment]
This buildpack has been deprecated (c06c1e31291c24f71e8d84225727887506c3c897), and it's also no longer possible for changes to be made to it, due to the issues mentioned in #61.
