### ISSUE TITLE
public folder failed to be deployed together

### ISSUE THREAD

**Issue by woosungchu** [heroku/heroku-buildpack-emberjs#28]
I set image asset into 'public' folder
![image](https://cloud.githubusercontent.com/assets/13829340/24276126/d2e8e5e8-1077-11e7-911f-ac7390eddc13.png)

if I..
```
ember b -e production
```

Local :
![image](https://cloud.githubusercontent.com/assets/13829340/24276082/7c24641c-1077-11e7-9404-5722f02a7b19.png)

Heroku:
![image](https://cloud.githubusercontent.com/assets/13829340/24276091/995d4c74-1077-11e7-9207-b4de5d2256b1.png)

Heroku ember buildpack doesn't seem bring public/assets folder

**Comment by woosungchu** [comment]
I have tried to find whether this similar issue happend before and I found issue about fingerprint configuration . But this case seem different with [that](http://stackoverflow.com/questions/25676548/ember-cli-heroku-deployment-cannot-access-public-folder)

**Comment by Dhaulagiri** [comment]
@woosungchu what if you move the images folder out of `assets` and into just the `public` folder?

**Comment by woosungchu** [comment]
@Dhaulagiri  Same results... 

![2](https://cloud.githubusercontent.com/assets/13829340/24384660/833f5884-13a0-11e7-8768-e5caa4586971.PNG)

**Comment by woosungchu** [comment]
It works in AWS cloudfront but not in heroku so far

**Comment by edmorley** [comment]
This buildpack has been deprecated (c06c1e31291c24f71e8d84225727887506c3c897), and it's also no longer possible for changes to be made to it, due to the issues mentioned in #61.
