### ISSUE TITLE
Build fails missing node-sass

### ISSUE THREAD

**Issue by oskarrough** [heroku/heroku-buildpack-emberjs#29]
Hi, if an app uses `node-sass` and https://github.com/n1ru4l/ember-cli-css-preprocess it fails to build on heroku. I assume it's because the `node-sass` dependency doesn't get installed. I have it in `devDependencies`.

What to do? Any help would appreciated, thank you!

```
remote: Build failed.
remote: The Broccoli Plugin: [StyleProcessor] failed with:
remote: Error: ENOENT: no such file or directory, scandir '/tmp/build_3d4e9d428e950cd6d265c45f01c45f05/node_modules/node-sass/vendor'
remote:     at Object.fs.readdirSync (fs.js:914:18)
remote:     at Object.getInstalledBinaries (/tmp/build_3d4e9d428e950cd6d265c45f01c45f05/node_modules/node-sass/lib/extensions.js:122:13)
remote:     at foundBinariesList (/tmp/build_3d4e9d428e950cd6d265c45f01c45f05/node_modules/node-sass/lib/errors.js:20:15)
remote:     at foundBinaries (/tmp/build_3d4e9d428e950cd6d265c45f01c45f05/node_modules/node-sass/lib/errors.js:15:5)
remote:     at Object.module.exports.missingBinary (/tmp/build_3d4e9d428e950cd6d265c45f01c45f05/node_modules/node-sass/lib/errors.js:45:5)
remote:     at module.exports (/tmp/build_3d4e9d428e950cd6d265c45f01c45f05/node_modules/node-sass/lib/binding.js:15:30)
remote:     at Object.<anonymous> (/tmp/build_3d4e9d428e950cd6d265c45f01c45f05/node_modules/node-sass/lib/index.js:14:35)
```

**Comment by Dhaulagiri** [comment]
@oskarrough are you using yarn?

**Comment by oskarrough** [comment]
@Dhaulagiri yes?

**Comment by Dhaulagiri** [comment]
This is likely an issue upstream in either the node buildpack or yarn itself from our experience.  We had a similar problem that can be solved by either setting the `NODE_MODULES_CACHE` config var to `false` or adding a postinstall script `postinstall: "npm rebuild"` to your package.json.

**Comment by oskarrough** [comment]
Thank you, probably. As it was working before.

So I tried replacing `ember-cli-css-preprocess` + `node-sass` with `ember-cli-sass` (which also uses `node-sass`) + `ember-cli-postcss` and now it builds on Heroku. FastBoot and all. Happy camper!

**Comment by hone** [comment]
@oskarrough sweet. I think this is related to [this issue](https://github.com/yarnpkg/yarn/issues/1981).
