### ISSUE TITLE
ember 2.13 support (no bower)

### ISSUE THREAD

**Issue by dbinetti** [heroku/heroku-buildpack-emberjs#32]
I'm sure I'm missing something since I know that Heroku itself is using both Ember and Yarn, but in any case I just upgraded to ember-cli 2.13, dropping Bower as a requirement.  However, when I deploy I get this error (relevant bits only):

```
-----> Installing Bower package manager
barberscore-ember@0.0.0 /tmp/build_524950f91b08e8a1c165342875e2b780
└── bower@1.8.0 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
-----> Installing Bower dependencies
bower                           ENOENT No bower.json present
```

And then it fails.  Using SemaphoreCI, FWIW. Is there a config or something I forgot to flip?

Thanks

**Comment by Dhaulagiri** [comment]
@dbinetti this is a known issue (https://github.com/heroku/heroku-buildpack-emberjs/issues/24) that, until fixed, can be worked around by leaving an empty bower.json in your project so that it will still deploy

**Comment by dbinetti** [comment]
Many thanks -- apparently I was searching for the wrong error.  Thanks
