### ISSUE TITLE
clean slug size for non-fastboot apps

### ISSUE THREAD

**Issue by hone** [heroku/heroku-buildpack-emberjs#37]
See #26, but we should be able to remove `node_modules` and `bower_components` for non fastboot apps to trim down the slug size. /cc @Dhaulagiri

**Comment by javve** [comment]
Any updates here? We recently got over the 500 mb limit and can no longer deploy our app.

**Comment by whatthewhat** [comment]
This would be a very welcome change 👍 
In the meantime what helped us is clearing the build cache: https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache (reduced the slug size from ~500MB to ~120MB)

**Comment by edmorley** [comment]
This buildpack has been deprecated (c06c1e31291c24f71e8d84225727887506c3c897), and it's also no longer possible for changes to be made to it, due to the issues mentioned in #61.
