### ISSUE TITLE
Content-Type for .json files is application/octet-stream

### ISSUE THREAD

**Issue by artinboghosian** [heroku/heroku-buildpack-emberjs#39]
We have an Ember app that is being displaying in an Android app WebView. To register the Android app as a handler for our urls we need to add a public/.well-known/assetlinks.json file to our Ember app that Google can then verify against. The problem is that when we deploy the Ember app and hit this path the response header contains a content-type of application/octet-stream instead of application/json.  However when running the Ember app locally the file is served correctly as application/json. As a result Google is unable to verify because they are expecting an application/json content-type.

**Comment by artinboghosian** [comment]
Solution was to add static.json file and set content-type in headers:

    {
      "headers": {
        "/.well-known/assetlinks.json": {
          "Content-Type": "application/json"
        }
      }
    }

**Comment by hone** [comment]
@artinboghosian thanks for filing this. This should definitely be recognized by default. I've gone ahead and [merged a PR](https://github.com/heroku/heroku-buildpack-static/pull/78) on the static buildpack for this. Can you try with these changes and see if it fixes your problem?
