### ISSUE TITLE
Is this thingo stable?

### ISSUE THREAD

**Issue by hhff** [heroku/heroku-buildpack-emberjs#4]
HI team!

Noticed there's no version number or anything here.  Is this bad-boy considered stable?  If so - could we cut a real release of it?

hx

**Comment by hone** [comment]
@hhff it's stable in the sense that I'm planning on maintaining it with some help from @Dhaulagiri. It's still somewhat experimental as we figure out what makes the best ember experience I can provide. What are you looking for in a "release"? a git tag?

**Comment by hhff** [comment]
Thanks @hone !  Mostly just wanted to know how reliable / stable this is.  No need for a git tag!
