### ISSUE TITLE
React warning in console

### ISSUE THREAD

**Issue by dbinetti** [heroku/heroku-buildpack-emberjs#40]
Is this related to the buildpack?  Can it be safely ignored?

```
Warning: It looks like you're using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster. See https://fb.me/react-minification for more details.
```
https://github.com/facebook/react/issues/6479

**Comment by hone** [comment]
@dbinetti hi, I've never seen this error message before. Are you using the ember.js buildpack to build react?

**Comment by dbinetti** [comment]
no, it's all ember.  must be a library I'm using.  I'll try to track down the source.  Sorry for the bother.

**Comment by hone** [comment]
no worries! good luck.
