### ISSUE TITLE
How to gzip and minify Fastboot enabled?

### ISSUE THREAD

**Issue by ivanhueso** [heroku/heroku-buildpack-emberjs#41]
How can I do to gzip and minify the .js files?

**Comment by oskarrough** [comment]
Haven't figured it out yet. Similar discussions in

https://github.com/heroku/heroku-buildpack-emberjs/issues/14
https://github.com/heroku/heroku-buildpack-emberjs/issues/20

Edit: try to force https and see if that also works for you https://github.com/heroku/heroku-buildpack-emberjs/issues/14#issuecomment-366220941

**Comment by edmorley** [comment]
This buildpack has been deprecated (c06c1e31291c24f71e8d84225727887506c3c897), and it's also no longer possible for changes to be made to it, due to the issues mentioned in #61.
