### ISSUE TITLE
No cache control header set on index.html

### ISSUE THREAD

**Issue by Subtletree** [heroku/heroku-buildpack-emberjs#42]
Deploying with this buildpack on dokku, my index.html is being cached due to no cache-control header.

Is this something the buildpack should be doing automatically or is there some config for this?

Cheers 🙂

**Comment by hone** [comment]
Weird. By design, the static buildpack isn't setting any default caching headers, but it looks like dokku is?

**Comment by Subtletree** [comment]
Sorry I meant the index.html **does not** have a cache-control header so it is being cached by default. 

Thanks for pointing me to the static buildpack to configure this.

For future (non fastboot) readers: https://github.com/heroku/heroku-buildpack-static#custom-headers
