### ISSUE TITLE
 Error waiting for process to terminate: No child processes 

### ISSUE THREAD

**Issue by robwebdev** [heroku/heroku-buildpack-emberjs#43]
When deploying an Heroku app using this buildpack I get an error in the logs `Error waiting for process to terminate: No child processes`. Everything works as expected but the error is noise that I could do without when monitoring the application.

```
Sep 13 11:11:40 ew-website heroku/web.1:  Restarting 
Sep 13 11:11:40 ew-website heroku/web.1:  State changed from up to starting 
Sep 13 11:11:41 ew-website heroku/web.1:  Stopping all processes with SIGTERM 
Sep 13 11:11:41 ew-website heroku/web.1:  Process exited with status 22 
Sep 13 11:11:41 ew-website app/web.1:  Error waiting for process to terminate: No child processes 
Sep 13 11:11:52 ew-website heroku/web.1:  Starting process with command `ember-fastboot dist --serve-assets-from dist --port 21180` 
```

After a bit of digging I found [this page](https://devcenter.heroku.com/articles/dynos#graceful-shutdown-with-sigterm) that suggests that the `SIGTERM` signal should be handled to shutdown the app gracefully. Would I be right in thinking that should happen somewhere in [fastboot-app-server](https://github.com/ember-fastboot/fastboot-app-server)?

**Comment by Dorian** [comment]
Got the same error today when running a rails command inside `heroku run`

**Comment by edmorley** [comment]
This buildpack has been deprecated (c06c1e31291c24f71e8d84225727887506c3c897), and it's also no longer possible for changes to be made to it, due to the issues mentioned in #61.
