### ISSUE TITLE
How to make this work with fastboot-app-server?

### ISSUE THREAD

**Issue by RobbieTheWagner** [heroku/heroku-buildpack-emberjs#44]
I tried manually configuring my procfile to run it, which worked, but then it could not find any of the assets and the app was broken. I tried running with this:

```
/* eslint-env node */
const FastBootAppServer = require('fastboot-app-server');

const server = new FastBootAppServer({
  distPath: 'dist',
  gzip: true,
  beforeMiddleware(app) {
    app.use((request, response, next) => {
      if (request.headers['x-forwarded-proto'] === 'https') {
        return next();
      } else {
        return response.redirect(301, `https://${request.hostname}${request.url}`);
      }
    });
  }
});

server.start();
```

**Comment by RobbieTheWagner** [comment]
Figured this out. Would be good to allow more customization with the build pack itself though.

**Comment by openhouse** [comment]
Hi @rwwagner90, I'm looking at adding custom middleware with fastboot-app-server.  Could you give a quick outline of your solution?  Thank you!

**Comment by RobbieTheWagner** [comment]
@openhouse I just added a vanilla fastboot-app-server setup in server.js and told my Procfile to use that. You can see my code at https://github.com/shipshapecode/shipshape.io

**Comment by allthesignals** [comment]
@rwwagner90 did you run into any performance issues running this on Heroku? do you remember how many dynos you had to use?

I tried to use vanilla fastboot app server but kept seeing memory overloads. I know this probably points to a memory leak in my app, but addressing that has been a rabbit hole.

**Comment by RobbieTheWagner** [comment]
@allthesignals I do remember there occasionally being memory issues, but they were random. Probably a memory leak as well.
