### ISSUE TITLE
Deploys are failing - Unable to download yarn: 404

### ISSUE THREAD

**Issue by beerlington** [heroku/heroku-buildpack-emberjs#47]
I'm getting an error when trying to deploy now:

```
Downloading and installing yarn (1.5.0)...
Unable to download yarn: 404
```
I took me a while to track down the issue on a related repo - https://github.com/heroku/heroku-buildpack-nodejs/issues/523

... with the fix being what was changed in https://github.com/artsy/metaphysics/pull/945/files

I figured I'd post this here since other people might run into this issue and not know where to look if they're only using this build pack.

**Comment by musaffa** [comment]
I'm experiencing this issue now. It never happened before. #56 Unpinning nodejs buildpack version may probably solve the issue.

cc @hone @Dhaulagiri

**Comment by Subtletree** [comment]
Just hit this now for the first time too. Pinning yarn as mentioned in the OP fix is working for me in the meantime

**Comment by fivetanley** [comment]
@Subtletree @musaffa @beerlington I merged #56, can you try again and let me know if it's working for you? Thanks

**Comment by fivetanley** [comment]
Actually hold up, we need someone to rebuild the toolchain since mrb is a compiled language. I'll update when we've done that.

**Comment by dja** [comment]
@fivetanley Any updates on this? We're blocked on all development and deployment.

**Comment by musaffa** [comment]
@dja For a short term solution, pin the exact yarn version you're using in the package.json's engines attribute. Don't use any semver symbol like ^, ~.

**Comment by vladucu** [comment]
@fivetanley @hone would it be possible to get a new release for this?

**Comment by fivetanley** [comment]
reopening this... without @hone's help i'm not sure we'll be able to get a new release out. since the buildpack is written in mruby it requires a compilation and upload step which no longer seems to work out of the box with the docker setup.

**Comment by bartocc** [comment]
I believe we've been hit by this today but because of a new nodejs version `12.18.3`:

```
-----> Fetching buildpack heroku/nodejs-v98
-----> Node.js detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
-----> Installing binaries
       engines.node (package.json):  12.*
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 12.* via semver.io...
       Downloading and installing node 12.18.3...
       Unable to download node 12.18.3; does it exist?
-----> Build failed
```

The buildpack still references `nodejs-v98`, despite PR https://github.com/heroku/heroku-buildpack-emberjs/pull/56 beeing merged.

A new build + upload of this buildpack would be great.

**Comment by danielleadams** [comment]
@bartocc can you clear your build cache? https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache

**Comment by flexyford** [comment]
> @bartocc can you clear your build cache? https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache

We're running into the same issue with nodejs 12.18.3. We cleared the build cache but are still fetching `buildpack heroku/nodejs-v98`

**Comment by bartocc** [comment]
hi @danielleadams , clearing the cache unfortunately did not work.

Here is the line building the URL to download on `buildpack heroku/nodejs-v98`: https://github.com/heroku/heroku-buildpack-nodejs/blob/v98/lib/binaries.sh#L47. And the URL it should build is https://s3pository.heroku.com/node/v12.18.3/node-v12.18.3-linux-x64.tar.gz, which actually exists…

So I do not understand why this builds are failing…

**Comment by bartocc** [comment]
@flexyford Have you found a solution to this?

**Comment by flexyford** [comment]
> @flexyford Have you found a solution to this?

@bartocc we have no found a proper solution yet, but you could always tie down your node version in `package.json` similar to what was proposed in https://github.com/heroku/heroku-buildpack-emberjs/issues/47#issuecomment-500689864

```js
"engines": {
  "node": "12.18.2"
},
```

**Comment by bartocc** [comment]
> > @flexyford Have you found a solution to this?
> 
> @bartocc we have no found a proper solution yet, but you could always tie down your node version in `package.json` similar to what was proposed in [#47 (comment)](https://github.com/heroku/heroku-buildpack-emberjs/issues/47#issuecomment-500689864)
> 
> ```js
> "engines": {
>   "node": "12.18.2"
> },
> ```

We did do that indeed, but it did not solve the issue 🤦‍♂️

**Comment by flexyford** [comment]
@bartocc really? Is it the same error message? You might also try specifying a range that ignores `12.18.3`...

```json
"engines": {
  "node": "12.x <12.18.3 || 12.x >12.18.3",
},
```

**Comment by bartocc** [comment]
ok, I just realized that I made a typo and specified `12.8.2` instead of `12.18.2` 🤦‍♂️

**Comment by rajveerappan** [comment]
See https://github.com/heroku/heroku-buildpack-emberjs/issues/61 for the node issue.

**Comment by imanuelgittens** [comment]
@flexyford I got the same issue after pinning my versions 

```
"engines": {
    "node": "12.13.1",
    "npm": "6.12.1",
    "yarn": "1.4.1"
  },
```

@bartocc did it work for you?

**Comment by edmorley** [comment]
This buildpack has been deprecated (c06c1e31291c24f71e8d84225727887506c3c897), and it's also no longer possible for changes to be made to it, due to the issues mentioned in #61.
