### ISSUE TITLE
Deploy sometimes builds as development environment

### ISSUE THREAD

**Issue by dja** [heroku/heroku-buildpack-emberjs#50]
On a few occasions now, when deploying from Github -> Heroku app, it builds as if it's in the development environment, with localhost-type variables. The only solution I've found to fixing it is to completely delete the app and redeploy to a brand new instance.

**Comment by Dhaulagiri** [comment]
@dja could you be more specific? What is making you think it's building for development and what side effects are you noticing in your app because of that?

**Comment by dja** [comment]
I see in the build logs that it sets the NODE_ENV properly to 'production', but when visiting the app, it shows development env variables (in the `<head>` of the index) and tries to start livereload

**Comment by dja** [comment]
Turns out it's an issue specifically to do with the listing of included buildpacks. On apps where I have nodejs buildpack listed after the emberjs buildpack, it does not treat the environment as production. If nodejs is listed first, it does.
