### ISSUE TITLE
Doesn't support FASTBOOT_DISABLED env variable

### ISSUE THREAD

**Issue by musaffa** [heroku/heroku-buildpack-emberjs#53]
`Ember-cli-fastboot` [supports](https://github.com/ember-fastboot/ember-cli-fastboot#disabling-fastboot-with-ember-serve) an environmental flag to disable Fastboot server like this:
```zsh
$ FASTBOOT_DISABLED=true ember serve
```
Since this buildpack uses `fastboot-cli`'s `ember-fastboot` command, we cannot avail this feature. Besides, we use `ember serve` in our development machine to test the features in dev and production environment. It would be nice to have parity with Heroku dyno about how we serve our ember apps. Had it been the case, the issue wouldn't have to be created in the first place.

Thanks.

**Comment by edmorley** [comment]
This buildpack has been deprecated (c06c1e31291c24f71e8d84225727887506c3c897), and it's also no longer possible for changes to be made to it, due to the issues mentioned in #61.
