### ISSUE TITLE
heroku review app builds fails with ember-cli-mirage 0.4.2 and up

### ISSUE THREAD

**Issue by adamhong** [heroku/heroku-buildpack-emberjs#54]
We're seeing the following issue in trying to build review apps using `ember-cli-mirage` versions 0.4.2 and up:

```
cleaning up...
Build failed.
Build Error (Funnel)
ENOENT: no such file or directory, lstat '/tmp/build_af258e1e37544ab864abf4c2c8a0d483/mirage'
Stack Trace and Error Report: /tmp/error.dump.c21e2460578eac925b1b24a3e95af543.log
```

everything seems to work fine locally. can only repro this issue on Heroku. any insight would be appreciated

**Comment by Dhaulagiri** [comment]
@adamhong that's puzzling, do you know if anything specific changed with mirage between 0.4.1 and 0.4.2 that might explain this on that side of things?

**Comment by adamhong** [comment]
i have a suspicion on what the change might have been thats causing the issue, but I'm not sure.

https://github.com/samselikoff/ember-cli-mirage/compare/v0.4.1...v0.4.2

At this point our best option is to fork and see if we can resolve. Was curious if there is anything specific about the buildpack that might explain. we're also asking the maintainers of `ember-cli-mirage` if they have any ideas

**Comment by Dhaulagiri** [comment]
Another potential path for working around this might be to try [this buildpack](https://github.com/heroku/heroku-buildpack-ember-cli) which is similar to the one here but is a bit more simple and straightforward to debug on if there are problems.  Hopefully you can figure out what is causing the issue on mirage's side or use this workaround to unblock you.

**Comment by adamhong** [comment]
@Dhaulagiri ~so i was actually able to repro this locally, from the build log we see the following command for build:~

`ember build --environment production 2>&1`

any idea why `2>&1` gets added? we're not using the `ember-cli-deploy` addon. could that be part of the issue?

Edit: actually the extra `2>&1` does not seem to make a difference

**Comment by adamhong** [comment]
thanks @Dhaulagiri will checkout that buildpack

**Comment by adamhong** [comment]
resolved by setting `excludeFilesFromBuild: true` for ember-cli-mirage for production as well. the expectation is that this should already be the case, but this setting is still required.
