### ISSUE TITLE
Blank page after deploy

### ISSUE THREAD

**Issue by andyw8** [heroku/heroku-buildpack-emberjs#55]
I realise this repo hasn't been updated for a while, so I'm not sure if it's expected to work with the latest Ember.

My app appears to deploy without errors, but when I try load in the browser the page is blank. There are no client-side errors in the console.

The full code is available here:
https://github.com/andyw8/ember-playground

It's deployed here:
https://sleepy-meadow-37593.herokuapp.com/

Here's the build log:
```
-----> emberjs app detected
-----> Setting NPM_CONFIG_PRODUCTION to false to install ember-cli toolchain
-----> Fetching buildpack heroku/nodejs-v98
-----> Node.js detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
-----> Installing binaries
       engines.node (package.json):  6.* || 8.* || >= 10.*
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 6.* || 8.* || >= 10.* via semver.io...
       Downloading and installing node 11.6.0...
       Using default npm version: 6.5.0-next.0
       Resolving yarn version (latest) via semver.io...
       Downloading and installing yarn (1.13.0)...
       Installed yarn 1.13.0
-----> Restoring cache
       Skipping cache restore (new runtime signature)
-----> Building dependencies
       Installing node modules (yarn.lock)
       yarn install v1.13.0
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       info fsevents@1.2.4: The platform "linux" is incompatible with this module.
       info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
       [3/4] Linking dependencies...
       [4/4] Building fresh packages...
       Done in 26.02s.
-----> Caching build
       Clearing previous node cache
       Saving 2 cacheDirectories (default):
       - node_modules
       - bower_components (nothing to cache)
-----> Build succeeded!
-----> Fetching buildpack heroku/ember-cli-deploy
-----> ember-cli detected
-----> Skipping installing bower dependencies, no bower.json detected.
-----> Building ember assets
WARNING: Node v11.6.0 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js. See https://git.io/v7S5n for details.
Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
Environment: production
Circular dependency: ../broccoli-3692hiX0vkpUWwh/cache-099-rollup/build/-private/system/model/model.js -> ../broccoli-3692hiX0vkpUWwh/cache-099-rollup/build/-private/system/model/internal-model.js -> ../broccoli-3692hiX0vkpUWwh/cache-099-rollup/build/-private/system/references.js -> ../broccoli-3692hiX0vkpUWwh/cache-099-rollup/build/-private/system/references/belongs-to.js -> ../broccoli-3692hiX0vkpUWwh/cache-099-rollup/build/-private/system/model/model.js
cleaning up...
Built project successfully. Stored in "dist/".
File sizes:
 - dist//assets/playground-2f8e349f1fa568e9874d07b833997cf3.css: 56 B (76 B gzipped)
 - dist//assets/playground-341c6a6163fc47c46f3c15202f5ac6bc.js: 57.17 KB (8.35 KB gzipped)
 - dist//assets/tailwind-9bfd643d30bc57b02e255c9a0615812f.css: 289.15 KB (48.45 KB gzipped)
 - dist//assets/vendor-3752583d75490eb1a77c6538df3b8eb5.js: 798.4 KB (200.67 KB gzipped)
 - dist//assets/vendor-d41d8cd98f00b204e9800998ecf8427e.css: 0 B
-----> Caching ember assets
-----> Writing static.json
-----> Fetching buildpack heroku/static
-----> Static HTML detected
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
-----> Installed directory to /app/bin
-----> Discovering process types
       Procfile declares types     -> (none)
       Default types for buildpack -> web
-----> Compressing...
       Done: 48.7M
-----> Launching...
       Released v3
       https://sleepy-meadow-37593.herokuapp.com/ deployed to Heroku
```

**Comment by Dhaulagiri** [comment]
🤔  that is quite odd. I'm able to reproduce this in a fresh app as well but I also know this buildpack to still be working with some projects we have that use it.  I'm not sure if I will have time to dig in here, but we do also have [this](https://github.com/heroku/heroku-buildpack-ember-cli) buildpack that we use for ember apps which I know is still working without issue.

**Comment by ijlee2** [comment]
Hello, I'd like to report experiencing similar issue. I installed a fresh Ember app (v 3.7.1). While the logs show a success message, I only see a blank page instead of Ember's default welcome page.

I will try the other buildpack suggested above, thanks.
```
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> emberjs app detected
remote: -----> Setting NPM_CONFIG_PRODUCTION to false to install ember-cli toolchain
remote: -----> Fetching buildpack heroku/nodejs-v98
remote: -----> Node.js detected
remote: 
remote: -----> Creating runtime environment
remote:        
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=false
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:        NODE_VERBOSE=false
remote: 
remote: -----> Installing binaries
remote:        engines.node (package.json):  6.* || 8.* || >= 10.*
remote:        engines.npm (package.json):   unspecified (use default)
remote:        
remote:        Resolving node version 6.* || 8.* || >= 10.* via semver.io...
remote:        Downloading and installing node 11.7.0...
remote:        Using default npm version: 6.5.0
remote: 
remote: -----> Restoring cache
remote:        Skipping cache restore (new runtime signature)
remote: 
remote: -----> Building dependencies
remote:        Installing node modules (package.json)
remote:        
remote:        > spawn-sync@1.0.15 postinstall /tmp/build_8bff8a7454910df0065bb27b8995727a/node_modules/spawn-sync
remote:        > node postinstall
remote:        
remote:        added 1222 packages from 620 contributors and audited 63192 packages in 30.195s
remote:        found 0 vulnerabilities
remote:        
remote: 
remote: -----> Caching build
remote:        Clearing previous node cache
remote:        Saving 2 cacheDirectories (default):
remote:        - node_modules
remote:        - bower_components (nothing to cache)
remote: 
remote: -----> Build succeeded!
remote: -----> Fetching buildpack heroku/ember-cli-deploy
remote: -----> ember-cli detected
remote: -----> Skipping installing bower dependencies, no bower.json detected.
remote: -----> Building ember assets
remote: WARNING: Node v11.7.0 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js. See https://git.io/v7S5n for details.
remote: Could not start watchman
remote: Visit https://ember-cli.com/user-guide/#watchman for more info.
remote: Environment: production
remote: Circular dependency: ../broccoli-303nekiFNSDHFiH/cache-064-rollup/build/-private/system/model/model.js -> ../broccoli-303nekiFNSDHFiH/cache-064-rollup/build/-private/system/model/internal-model.js -> ../broccoli-303nekiFNSDHFiH/cache-064-rollup/build/-private/system/references.js -> ../broccoli-303nekiFNSDHFiH/cache-064-rollup/build/-private/system/references/belongs-to.js -> ../broccoli-303nekiFNSDHFiH/cache-064-rollup/build/-private/system/model/model.js
remote: cleaning up...
remote: Built project successfully. Stored in "dist/".
remote: File sizes:
remote:  - dist//assets/****.css: 0 B
remote:  - dist//assets/****.js: 4.77 KB (1.36 KB gzipped)
remote:  - dist//assets/vendor-****..js: 736.66 KB (191.99 KB gzipped)
remote:  - dist//assets/vendor-****.css: 0 B
remote: -----> Caching ember assets
remote: -----> Writing static.json
remote: -----> Fetching buildpack heroku/static
remote: -----> Static HTML detected
remote:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
remote:                                  Dload  Upload   Total   Spent    Left  Speed
remote: 100  838k  100  838k    0     0  10.4M      0 --:--:-- --:--:-- --:--:-- 10.4M
remote: -----> Installed directory to /app/bin
remote: -----> Discovering process types
remote:        Procfile declares types     -> (none)
remote:        Default types for buildpack -> web
remote: 
remote: -----> Compressing...
remote:        Done: 46.7M
remote: -----> Launching...
remote:        Released v3
remote:        https://****.herokuapp.com/ deployed to Heroku
remote: 
remote: Verifying deploy... done.
```

**Comment by ijlee2** [comment]
The blank page problem also occurred on a new 3.6, 3.1.4, and 2.18 app. I have an 3.1.4 app built in August 2018 that still works on Heroku.

Update: I found the problem. It's the `ember-welcome-page` addon that doesn't render. Was able to edit `application.hbs` to just say `Hello world` and get it to show up on 3.7 using the buildpack.

**Comment by Dhaulagiri** [comment]
I wonder if the problem isn't with some change in ember-cli or some other dependency in the build pipeline and not with Ember itself

**Comment by Dhaulagiri** [comment]
Ahh, seeing @ijlee2's edited comment now that makes more sense! I wonder what has changed with that addon that would cause this 🤔

**Comment by ijlee2** [comment]
@Dhaulagiri I asked the Ember core team. The behavior that we don't see `ember-welcome-page` in production is correct. It was to avoid shipping unnecessary resources.

**Comment by Dhaulagiri** [comment]
🤦‍♂️ oh that makes a lot more sense now.

I'm going to close this issue then.

**Comment by kallonbundu** [comment]
My django project is showing blank after a successful deployment




$ git push heroku main
Enumerating objects: 11, done.
Counting objects: 100% (11/11), done.
Delta compression using up to 4 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 739 bytes | 739.00 KiB/s, done.
Total 6 (delta 5), reused 0 (delta 0), pack-reused 0
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Building on the Heroku-20 stack
remote: -----> Using buildpack: heroku/php
remote: -----> PHP app detected
remote:
remote:        NOTICE: Your 'composer.json' is completely empty!
remote:
remote:        A completely empty file is not a valid JSON document.
remote:
remote:        Heroku automatically corrected this problem, but it is strongly
remote:        recommended you change the contents to at least '{}'.
remote:
remote:        For documentation on Composer and dependency management, check
remote:        out the introduction at https://getcomposer.org/doc/00-intro.md
remote:
remote: -----> Bootstrapping...
remote: -----> Preparing platform package installation...
remote:        NOTICE: No runtime required in composer.lock; using PHP ^7.3.0 | ^8.0.0
remote: -----> Installing platform packages...
remote:        - apache (2.4.53)
remote:        - php (8.1.5)
remote:        - composer (1.10.26)
remote:        - nginx (1.20.2)
remote: -----> Installing dependencies...
remote:        Composer version 1.10.26 2022-04-13 16:39:56
remote: -----> Preparing runtime environment...
remote:        NOTICE: No Procfile, using 'web: heroku-php-apache2'.
remote: -----> Checking for additional extensions to install...
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote:
remote: -----> Compressing...
remote:        Done: 23.2M
remote: -----> Launching...
remote:        Released v4
remote:        https://socialtarget.herokuapp.com/ deployed to Heroku
remote:
remote: Verifying deploy... done.
To https://git.heroku.com/socialtarget.git
   4394ae7..f2dd00d  main -> main

**Comment by kallonbundu** [comment]
Django app show blank after a successful deployment on heroku 
_______________________________________________________________________

$ git push heroku main
Enumerating objects: 11, done.
Counting objects: 100% (11/11), done.
Delta compression using up to 4 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 739 bytes | 739.00 KiB/s, done.
Total 6 (delta 5), reused 0 (delta 0), pack-reused 0
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Building on the Heroku-20 stack
remote: -----> Using buildpack: heroku/php
remote: -----> PHP app detected
remote:
remote:        NOTICE: Your 'composer.json' is completely empty!
remote:
remote:        A completely empty file is not a valid JSON document.
remote:
remote:        Heroku automatically corrected this problem, but it is strongly
remote:        recommended you change the contents to at least '{}'.
remote:
remote:        For documentation on Composer and dependency management, check
remote:        out the introduction at https://getcomposer.org/doc/00-intro.md
remote:
remote: -----> Bootstrapping...
remote: -----> Preparing platform package installation...
remote:        NOTICE: No runtime required in composer.lock; using PHP ^7.3.0 | ^8.0.0
remote: -----> Installing platform packages...
remote:        - apache (2.4.53)
remote:        - php (8.1.5)
remote:        - composer (1.10.26)
remote:        - nginx (1.20.2)
remote: -----> Installing dependencies...
remote:        Composer version 1.10.26 2022-04-13 16:39:56
remote: -----> Preparing runtime environment...
remote:        NOTICE: No Procfile, using 'web: heroku-php-apache2'.
remote: -----> Checking for additional extensions to install...
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote:
remote: -----> Compressing...
remote:        Done: 23.2M
remote: -----> Launching...
remote:        Released v4
remote:        https://socialtarget.herokuapp.com/ deployed to Heroku
remote:
remote: Verifying deploy... done.
To https://git.heroku.com/socialtarget.git
   4394ae7..f2dd00d  main -> main
