### ISSUE TITLE
ember-fastboot command not found

### ISSUE THREAD

**Issue by Dhaulagiri** [heroku/heroku-buildpack-emberjs#6]
This is likely an issue upstream, but I thought I'd log it here to start.  There seems to be a problem if your app is not using Node 5/npm 3 where ember-fastboot-server does not get installed and your app subsequently fails to boot like this:

```
2016-04-30T20:33:12.860833+00:00 heroku[web.1]: Starting process with command `ember-fastboot dist --serve-assets-from dist --port 59798`
2016-04-30T20:33:14.902493+00:00 app[web.1]: bash: ember-fastboot: command not found
```

I was able to solve this in my Node 4/npm 2 app with `npm install --save-dev ember-fastboot-server`.

**Comment by ghost** [comment]
I have the same problem with the latest Node 6.1.x and npm 3.8.

**Comment by Dhaulagiri** [comment]
I think my analysis of the problem here may have been incorrect as there have been changes to fastboot which may be the culprit

**Comment by dustinfarris** [comment]
Looks like we should be using fastboot-app-server now https://github.com/ember-fastboot/fastboot/blob/master/docs/deprecations.md#ember-fastboot-server-deprecated

**Comment by hone** [comment]
yeah, there needs to be a CLI component added still. if this will take longer, I'll look into rolling a simple `server.js`, but i'd like to avoid that if possible. /cc @tomdale

**Comment by tomdale** [comment]
@hone I will work on adding this back today.

**Comment by tomdale** [comment]
@hone I released fastboot-CLI yesterday, you should install that if you detect ember-CLI-fastboot.

**Comment by hone** [comment]
Thanks @tomdale I'll take a look at trying to implement this today.

**Comment by hone** [comment]
Fixed this [here](https://github.com/heroku/heroku-buildpack-ember-cli-deploy/commit/137c9c4d9ccfe8047ed6463a907ecd94ef6168c8) and pushed a new release out. Let me know if anyone is still running into this.
