### ISSUE TITLE
Support for forcing HTTPS

### ISSUE THREAD

**Issue by mike-north** [heroku/heroku-buildpack-emberjs#8]
It would be excellent if we could figure out how to do this in a way that works across both the static and nodejs buildpacks (meaning the user doesn't have to care about whether their app is in "fastboot mode" or not)

**Comment by maletor** [comment]
@mike-north, [I think it does](https://github.com/heroku/heroku-buildpack-ember-cli-deploy/blob/05e836ad829beda0b10bcc6cb0deed5f5db0c3ba/buildpack/mrblib/buildpack/commands/compile/default_static_config.rb#L24).

Just define a `static.json` file in the root of your project.

**Comment by mike-north** [comment]
@maletor as far as I can see, this only would affect the static buildpack (the one used for a non-fastboot app)

**Comment by maletor** [comment]
You're right. What do you propose? I can see issues with using the same JSON file.

**Comment by mike-north** [comment]
I think that we need another config in the node.js buildpack that does something similar (redirects non-https traffic to https). This way developers could put both in place and then add/remove fastboot and see no change in http vs. https behavior.

**Comment by hone** [comment]
potentially, this should be a thing added to the new [fastboot-app-server](https://github.com/ember-fastboot/fastboot-app-server). At some point, I'd like to explore fronting fastboot apps with nginx, but need to look into how tricky that'd be and managing multiple processes on a single dyno.

**Comment by t4t5** [comment]
@mike-north Did you guys find a workaround for this issue?

**Comment by jsquirrelz** [comment]
Is there currently a way to do this with the static buildpack? I opened an issue [here](https://github.com/heroku/heroku-buildpack-ember-cli/issues/13) about the redirects not happening despite the presumed correct configuration. BTW, is this the main ember buildpack repo? If so, I can close the other issue.

**Comment by hone** [comment]
Yeah, this is the main ember buildpack repo.

**Comment by sgasser** [comment]
Any news? Coming soon? How we could hep?

**Comment by hone** [comment]
I haven't had time to really tackle this, but the thought in my head 
would be figuring out how to front a fastboot app with the static 
buildpack and get the nginx upstream working nicely.

**Comment by jakeleboeuf** [comment]
What's the status here?

**Comment by FutoRicky** [comment]
Anyone found a solution?

**Comment by stephanebruckert** [comment]
Adding the static file does what I need https://stackoverflow.com/questions/47795457/ember-force-https-with-heroku

**Comment by musaffa** [comment]
Need this feature for Fastboot apps. This is such an important feature! Any update?

**Comment by oskarrough** [comment]
@musaffa, try @stephanebruckert advice above. What worked for was adding a Procfile and this snippet https://github.com/oskarrough/ember-fastboot-now-deployment-example/commit/3d2bdde8222522d2252023c685bba41e78d06001

**Comment by musaffa** [comment]
`static.json` is only for static buildpack.

@oskarrough I tried your way in Heroku but I get this error: `Cannot find module 'fastboot-app-server'`

**Comment by oskarrough** [comment]
Try to check how it is set up here https://github.com/oskarrough/ember-fastboot-now-deployment-example/tree/heroku. Basic idea is…

1. [`Procfile`](https://github.com/oskarrough/ember-fastboot-now-deployment-example/blob/heroku/Procfile) decides which command is used to start fastboot on Heroku. I run an NPM script called [`start-fastboot`](https://github.com/oskarrough/ember-fastboot-now-deployment-example/blob/heroku/package.json#L17).
2.  This npm script runs a node file called [`fastboot-server.js`](https://github.com/oskarrough/ember-fastboot-now-deployment-example/blob/heroku/fastboot-server.js). In this file we also make sure to redirect to HTTPS. It requires `fastboot-app-server` to be installed so you'll have to `npm i --save fastboot-app-server`.

**Comment by musaffa** [comment]
I did exactly that. I've added a Procfile which points to the npm script. I've also added `fastboot-app-server` as a dependency in `package.json`.

Have you tried your app in Heroku?

**Comment by oskarrough** [comment]
@musaffa hmm… it used to work, as can be seen here: https://serene-lake-99852.herokuapp.com/. But I just attempted to deploy the same repo again and now I get the same error as you. Not sure what's up.

**Comment by musaffa** [comment]
I've ssh-ed into my Heroku app repository and I cannot see `fastboot-app-server` in the node modules folder.

**Comment by musaffa** [comment]
I've ssh-ed into my Heroku app repository and I cannot see fastboot-app-server in the node modules folder. For some reason, it doesn't install `fastboot-app-server` whether it is in the devDependencies or dependencies.

**Comment by musaffa** [comment]
I've solved this problem. There's no need to add `fastboot-app-server` as a dependency. `heroku-buildpack-emberjs` installs `fastboot-cli` which has a dependency on `fastboot-app-server`. This `fastboot-app-server` module is hoisted to root dependencies. `require('fastboot-app-server')` will just work. Now the application is not crashing. Gzipping and Forcing HTTPs are also working.

But If you really want to add `fastboot-app-server` as a dependency and there's version mismatch with the one in `fastboot-cli`, then the `fastboot-app-sever` of `fastboot-cli` will be pushed to its own node_modules. So, in that case you will have to replace `require('fastboot-app-server')` with `require('fastboot-cli/node_modules/fastboot-app-server')`.

**Comment by musaffa** [comment]
I've ended up forking fastboot-cli where I've added [gzip and forced HTTPs support](https://github.com/musaffa/fastboot-cli/blob/master/bin/ember-fastboot#L39-L49) in its fastboot-app-server configuration. Add the forked `fastboot-cli` as a dependency by
```Bash
$ yarn add https://github.com/musaffa/fastboot-cli
```
`heroku-buildpack-emberjs` will install this forked `fastboot-cli` instead of the one in the npm repository. Neither `Procfile` nor `fastboot-app-server` configuration is needed. Everything will just work.

**Comment by donaldwasserman** [comment]
@musaffa That works great. Is there a way to upstream that with some sort of configuration option?

**Comment by musaffa** [comment]
@hone said he is trying to make it work by fronting the fastboot apps with nginx like the static buildpack. That will be a more robust solution.

**Comment by edmorley** [comment]
This buildpack has been deprecated (c06c1e31291c24f71e8d84225727887506c3c897), and it's also no longer possible for changes to be made to it, due to the issues mentioned in #61.
