### ISSUE TITLE
Disable ember-cli-deploy check

### ISSUE THREAD

**Issue by knownasilya** [heroku/heroku-buildpack-emberjs#9]
Is there a way to disable the ember-cli-deploy, since mine is setup for pagefront and I don't want to remove it.

**Comment by hone** [comment]
@knownasilya Hi, there currently isn't a way to do it now. What's your `ember-cli-deploy` setup right now? Can you paste your `package.json`?

**Comment by knownasilya** [comment]
``` json
"ember-cli-deploy": "0.5.1",
"ember-pagefront": "0.9.9",
```

**Comment by hone** [comment]
Thanks! I have an idea on how I can work around this, but it might take me
a bit to get to it.

**Comment by GabKlein** [comment]
It would be very useful to be able to disabled ember-cli-deploy

**Comment by edmorley** [comment]
This buildpack has been deprecated (c06c1e31291c24f71e8d84225727887506c3c897), and it's also no longer possible for changes to be made to it, due to the issues mentioned in #61.
